name: Manual Build
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: 54.154.243.219
          username: ec2-user
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            cd /var/www/kaishi
            git pull https://adams-okode:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
            rm -rf .env && cp .env.example .env
            /usr/local/bin/composer install --no-interaction
            ls 
            php artisan key:generate
            php artisan clear-compiled
            php artisan optimize
